# By default, SwiftLint uses a set of sensible default rules you can adjust:
# parent_config: .swiftlint_base.yml

included:
  - Packages/Features
  - Numbers

excluded:
  - Packages/Dependencies
  - Packages/*/*/.build
  - Packages/*/*/Tests
  - Packages/AutoMockable.generated.swift
  - Packages/Features/*/Tests/*.*
  #- Packages/*/*/*/*/API.swift
